### ISSUE TITLE
Fix doc warnings

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/QuantEcon.py#287] opened 2017-02-23 05:21 UTC
* [ ] Unknown sections
  - Unknown section Return
  - Unknown section Parameters:
  - Unknown section Returns:

Example: https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/cartesian.py#L16
Change `Parameters:` to `Parameters`

**Comment by oyamad** [comment] 2017-02-23 05:23
* [ ] WARNING: Block quote ends without a blank line; unexpected unindent.

```py
/Applications/anaconda/lib/python3.6/site-packages/quantecon/game_theory/mclennan_tourky.py:docstring of quantecon.game_theory.mclennan_tourky.mclennan_tourky:18: WARNING: Block quote ends without a blank line; unexpected unindent.
/Applications/anaconda/lib/python3.6/site-packages/quantecon/game_theory/normal_form_game.py:docstring of quantecon.game_theory.normal_form_game.NormalFormGame:10: WARNING: Block quote ends without a blank line; unexpected unindent.
/Applications/anaconda/lib/python3.6/site-packages/quantecon/game_theory/normal_form_game.py:docstring of quantecon.game_theory.normal_form_game.Player.best_response:6: WARNING: Block quote ends without a blank line; unexpected unindent.
/Applications/anaconda/lib/python3.6/site-packages/quantecon/game_theory/normal_form_game.py:docstring of quantecon.game_theory.normal_form_game.Player.best_response:17: WARNING: Block quote ends without a blank line; unexpected unindent.
/Applications/anaconda/lib/python3.6/site-packages/quantecon/game_theory/normal_form_game.py:docstring of quantecon.game_theory.normal_form_game.Player.best_response:34: WARNING: Block quote ends without a blank line; unexpected unindent.
/Applications/anaconda/lib/python3.6/site-packages/quantecon/game_theory/normal_form_game.py:docstring of quantecon.game_theory.normal_form_game.Player.payoff_vector:12: WARNING: Block quote ends without a blank line; unexpected unindent.
/Applications/anaconda/lib/python3.6/site-packages/quantecon/game_theory/random.py:docstring of quantecon.game_theory.random.covariance_game:24: WARNING: Block quote ends without a blank line; unexpected unindent.
/Applications/anaconda/lib/python3.6/site-packages/quantecon/game_theory/random.py:docstring of quantecon.game_theory.random.random_game:17: WARNING: Block quote ends without a blank line; unexpected unindent.
/Applications/anaconda/lib/python3.6/site-packages/quantecon/markov/core.py:docstring of quantecon.markov.core.MarkovChain.is_aperiodic:0: WARNING: Block quote ends without a blank line; unexpected unindent.
/Applications/anaconda/lib/python3.6/site-packages/quantecon/markov/core.py:docstring of quantecon.markov.core.MarkovChain.num_recurrent_classes:3: WARNING: Block quote ends without a blank line; unexpected unindent.
/Applications/anaconda/lib/python3.6/site-packages/quantecon/markov/core.py:docstring of quantecon.markov.core.MarkovChain.recurrent_classes:0: WARNING: Block quote ends without a blank line; unexpected unindent.
/Applications/anaconda/lib/python3.6/site-packages/quantecon/markov/core.py:docstring of quantecon.markov.core.mc_sample_path:27: WARNING: Block quote ends without a blank line; unexpected unindent.
/Applications/anaconda/lib/python3.6/site-packages/quantecon/markov/ddp.py:docstring of quantecon.markov.ddp.DiscreteDP.operator_iteration:12: WARNING: Block quote ends without a blank line; unexpected unindent.
/Applications/anaconda/lib/python3.6/site-packages/quantecon/markov/ddp.py:docstring of quantecon.markov.ddp.DiscreteDP.operator_iteration:13: WARNING: Block quote ends without a blank line; unexpected unindent.
/Applications/anaconda/lib/python3.6/site-packages/quantecon/markov/random.py:docstring of quantecon.markov.random.random_discrete_dp:45: WARNING: Block quote ends without a blank line; unexpected unindent.
/Applications/anaconda/lib/python3.6/site-packages/quantecon/markov/random.py:docstring of quantecon.markov.random.random_markov_chain:27: WARNING: Block quote ends without a blank line; unexpected unindent.
/Applications/anaconda/lib/python3.6/site-packages/quantecon/markov/random.py:docstring of quantecon.markov.random.random_stochastic_matrix:26: WARNING: Block quote ends without a blank line; unexpected unindent.
/Applications/anaconda/lib/python3.6/site-packages/quantecon/markov/random.py:docstring of quantecon.markov.random.random_stochastic_matrix:31: WARNING: Block quote ends without a blank line; unexpected unindent.
/Applications/anaconda/lib/python3.6/site-packages/quantecon/random/utilities.py:docstring of quantecon.random.utilities.probvec:20: WARNING: Block quote ends without a blank line; unexpected unindent.
/Applications/anaconda/lib/python3.6/site-packages/quantecon/random/utilities.py:docstring of quantecon.random.utilities.sample_without_replacement:24: WARNING: Block quote ends without a blank line; unexpected unindent.
/Applications/anaconda/lib/python3.6/site-packages/quantecon/compute_fp.py:docstring of quantecon.compute_fp.compute_fixed_point:57: WARNING: Block quote ends without a blank line; unexpected unindent.
```

**Comment by oyamad** [comment] 2017-02-23 05:25
* [ ] WARNING: Inline * start-string without end-string.

```py
/Applications/anaconda/lib/python3.6/site-packages/quantecon/markov/ddp.py:docstring of quantecon.markov.ddp.DiscreteDP:85: WARNING: Inline substitution_reference start-string without end-string.
/Applications/anaconda/lib/python3.6/site-packages/quantecon/quad.py:docstring of quantecon.quad.quadrect:13: WARNING: Inline emphasis start-string without end-string.
/Applications/anaconda/lib/python3.6/site-packages/quantecon/quad.py:docstring of quantecon.quad.quadrect:13: WARNING: Inline strong start-string without end-string.
```

**Comment by mmcky** [comment] 2017-02-23 05:29
Thanks @oyamad. This is helpful. I will add a review of readthedocs to my list.

**Comment by mmcky** [comment] 2017-02-23 05:45
The page: 

http://quanteconpy.readthedocs.io/en/latest/game_theory/lemke_howson.html

doesn't seem to be bringing the docstring through.

http://quanteconpy.readthedocs.io/en/latest/game_theory/mclennan_tourky.html
http://quanteconpy.readthedocs.io/en/latest/game_theory/pure_nash.html
http://quanteconpy.readthedocs.io/en/latest/game_theory/support_enumeration.html

on readthedocs

**Comment by oyamad** [comment] 2017-02-23 06:01
And this page:
http://quanteconpy.readthedocs.io/en/latest/game_theory/utilities.html

Also this page has not been updated:
http://quanteconpy.readthedocs.io/en/latest/tools/compute_fp.html

**Comment by oyamad** [comment] 2017-02-23 06:13
These pages display the docstrings locally on my machine.

**Comment by oyamad** [comment] 2017-02-23 06:20
I guess [this line](https://github.com/QuantEcon/QuantEcon.py/blob/master/rtd-environment.yml#L58) has to be updated.

Does any process update this file `rtd-environment.yml` automatically?

**Comment by mmcky** [comment] 2017-02-23 06:36
This is looking better: http://quanteconpy.readthedocs.io/en/rtd-env-update/
Once it passes tests I will merge to fix missing pages.

**Comment by mmcky** [comment] 2017-02-23 06:42
Some of this has now been addressed:

 - [x] fix missing documentation from pages above
 - [ ] review warning information from readthedocs

**Comment by oyamad** [comment] 2017-02-23 06:45
Very good.

What is the difference between "stable" and "latest"? I thought "stable" is from the released version and "latest" from `master`, but it seems not the case.

**Comment by mmcky** [comment] 2017-02-23 06:47
we just had the same thought :). I am looking into that now in the rtd setup. I agree. I think stable should be the latest release and latest should be master.

**Comment by mmcky** [comment] 2017-02-23 06:58
ah ha. So the adjustments we've made to documentation isn't contained in ``0.3.4`` so the ``stable`` won't reflect those changes as it is in the pre-updated state. I will disable ``stable`` for now in ``rtd`` and then we can fix this by issuing a new release ``0.3.5``.

**Comment by mmcky** [comment] 2017-02-23 06:59
I have also reset rtd ``stable`` and checked the build process and it is now pointing to the latest release hash.

**Comment by oyamad** [comment] 2017-02-23 07:12
`latest` is showing the released `0.3.4` rather than `master`. Is this what you expect?

**Comment by mmcky** [comment] 2017-02-23 07:18
``latest`` is building ``7cc7943ad3dff8755e70c61f6964d70901366c0e`` which is the last commit on ``master``.

**Comment by oyamad** [comment] 2017-02-23 07:28
For example, in http://quanteconpy.readthedocs.io/en/latest/game_theory/lemke_howson.html:
Functions other than `lemke_howson` are private functions, to which `_` have been added on `master`, so they should not show up in the documentation.

Do we really need the `- quantecon` entry in the `- pip` list in `rtd-environment.yml`? Wouldn't RTD run `python setup.py install` without it?

**Comment by oyamad** [comment] 2017-02-23 12:59
See #291 where `setup_py_install: true` is added to `readthedocs.yml`.

**Comment by mmcky** [comment] 2017-02-23 22:05
Another task 

- [ ] review latex code throughout documentation site for proper rendering, new lines etc. [Assign to QuantEcon RA during early March workshop]

**Comment by shizejin** [comment] 2017-02-24 13:10
The Warning message `Block quote ends without a blank line; unexpected unindent.` could be solved by adding a new line between the type and description of parameters, e.g.

```
random_state : scalar(int) or np.random.RandomState,
                   optional(default=None)
        Random seed (integer) or np.random.RandomState instance to set
        the initial state of the random number generator for
        reproducibility. If None, a randomly initialized RandomState is
        used.
```

to

```
random_state : scalar(int) or np.random.RandomState,
                   optional(default=None)

        Random seed (integer) or np.random.RandomState instance to set
        the initial state of the random number generator for
        reproducibility. If None, a randomly initialized RandomState is
        used.
```

But I don't know if it's a proper way, as usually there is no such empty line in most of docstrings.

**Comment by mmcky** [comment] 2017-02-26 00:49
Hi @shizejin. Thanks for looking into this issue. According to [numpydoc](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt) style guide, having no space is preferred. I will take a closer look at autodoc to see why this warning is getting raised and get back to you.

**Comment by oyamad** [comment] 2017-02-26 08:01
The problem is that the list of parameter types is too long that

```py
def random_game(nums_actions, random_state=None):
    """
    ...

    Parameters
    ----------
    ...

    random_state : scalar(int) or np.random.RandomState, optional(default=None)
```

would exceed the maximum line length 72 for docstrings.

One option is to shorten the description to

```py
    random_state : int or np.random.RandomState, optional(default=None)
```

or

```py
    random_state : scalar(int) or np.random.RandomState, optional
```

**Comment by shizejin** [comment] 2017-02-26 08:23
It seems that docs of Numpy are using the latter one, and declare the default value in the detailed descriptions of parameters. Should I apply this modification to the files with warning messgaes?

**Comment by oyamad** [comment] 2017-02-26 08:29
What are the other cases that yield the `unexpected unindent` warning?

**Comment by shizejin** [comment] 2017-02-26 11:56
I have checked all the `Block quote ends without a blank line; unexpected unindent.` warning message, and they are all in this case.

**Comment by shizejin** [comment] 2017-02-26 12:25
Other than these warnings, the only one left is `/quantecon/markov/ddp.py:docstring of quantecon.markov.ddp.DiscreteDP:85: WARNING: Inline substitution_reference start-string without end-string.`

```
* Transition probabilities q(s'|s, a):

q(0|0, 0) = 0.5, q(1|0, 0) = 0.5,
q(0|0, 1) = 0,   q(1|0, 1) = 1,
q(0|1, 0) = 0,   q(1|1, 0) = 1
```

And this is caused by using `s'`. As it is not appropriate to bracket it with "`", maybe we could replace it with another expression?

**Comment by oyamad** [comment] 2017-02-26 12:49
@shizejin Will you change all the `s'` in the docstring of `DiscreteDP` (lines 121-284) and in `solve` (line 651) to `s_next` (and keep the others)? Thanks!

**Comment by oyamad** [comment] 2017-02-26 12:52
There is one more in [compute_fp.py](https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/compute_fp.py#L89-L91).

Please change

```py
    method : str in {'iteration', 'imitation_game'},
             optional(default='iteration')
        Method of computing an approximate fixed point
```

to

```py
    method : str in {'iteration', 'imitation_game'}, optional
        Method of computing an approximate fixed point
        (default='iteration')
```

**Comment by oyamad** [comment] 2017-02-26 12:56
Regarding `random_state`:

Please change

```py
    random_state : scalar(int) or np.random.RandomState,
                   optional(default=None)
```

to

```py
    random_state : int or np.random.RandomState, optional(default=None)
```

(I think this looks better.)

**Comment by shizejin** [comment] 2017-02-26 14:20
Changes have been done.

Other than cases that can be solved by changing `scalar(int)` to `int` and `optional(default=None)` to `optional`, there are two types of `Block quote ends without a blank line; unexpected unindent.` warning messgaes left.

1. In [ddp.py](https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/markov/ddp.py#L642-L645) and [random.py](https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/markov/random.py#L87-L88), with long sets, e.g.

```
method : str in {'value_iteration', 'vi', 'policy_iteration',
                     'pi', 'modified_policy_iteration', 'mpi'},
            optinal(default='policy_iteration')
            Solution method.
```

2. In [normal_form_game.py](https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/game_theory/normal_form_game.py#L392-L393),

```
    data : array_like(Player) or array_like(int, ndim=1) or
           array_like(float, ndim=2 or N+1)
```

How to deal with these?

**Comment by mmcky** [comment] 2017-02-26 22:14
Hey @shizejin and @oyamad. Just letting you know I am running some setup workshops today for some new QuantEcon RA's. So I won't get to look into this issue until tomorrow (most likely). I wonder if there is a ``numpydoc`` linter that we can use? It might be a useful approach to catch these errors in the editor.

**Comment by oyamad** [comment] 2017-03-10 15:06
@shizejin

1. Please change
```py
        method : str in {'value_iteration', 'vi', 'policy_iteration',
                         'pi', 'modified_policy_iteration', 'mpi'},
                 optinal(default='policy_iteration')
            Solution method.
```
to
```py
        method : str, optinal(default='policy_iteration')
            Solution method, str in {'value_iteration', 'vi',
            'policy_iteration', 'pi', 'modified_policy_iteration',
            'mpi'}.
```
and
```py
    format : str in {'bsr', 'csr', 'csc', 'coo', 'lil', 'dia', 'dok'},
             optional(default='csr')
        Sparse matrix format. Relevant only when sparse=True.
```
to
```py
    format : str, optional(default='csr')
        Sparse matrix format, str in {'bsr', 'csr', 'csc', 'coo', 'lil',
        'dia', 'dok'}. Relevant only when sparse=True.
```

2. Change
```py
    data : array_like(Player) or array_like(int, ndim=1) or
           array_like(float, ndim=2 or N+1)
```
to
```py
    data : array_like of Player, int (ndim=1), or float (ndim=2 or N+1)
```

Thanks!

**Comment by shizejin** [comment] 2017-03-12 05:45
Sure. I have done these changes.

Also, in the `normal_form_game.py`, I change

```python
        opponents_actions : array_like(int or array_like(float)) or
                            array_like(int, ndim=1) or scalar(int)
```

to

```python
        opponents_actions : array_like(int or array_like(float)) or int
```

I omit "array_like(int, ndim=1)" as I think it is included in "array_like(int or array_like(float))", and otherwise I can not shorten the sentence to be under 79. Do you think this change is acceptable?

Now that there is no any warning message, I will do PR if you think it's okay.

**Comment by oyamad** [comment] 2017-03-14 14:59
"array_like(int, ndim=1)" should have been "array_like(float, ndim=1)".
The maximum line length is 72 for docstrings, if we want to strictly follow [PEP 8](https://www.python.org/dev/peps/pep-0008/#maximum-line-length).

What about just
```py
        opponents_actions : scalar(int) or array_like
```

**Comment by shizejin** [comment] 2017-03-14 15:31
Looks concise and accurate. Should I do PR based on this?

**Closed** 2017-03-19 22:59 UTC
