### ISSUE TITLE
Test needed for `kalman`

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.py#200] opened 2015-09-28 15:34 UTC
`stationary_coefficients` needs a test.  See this discussion:

https://github.com/QuantEcon/QuantEcon.py/pull/199

**Comment by mmcky** [comment] 2017-03-01 08:02
@lbui01 this isn't urgent -- but with your skills at writing tests. Do you think you might be able to take a look at this one?

**Comment by lbui01** [comment] 2017-03-01 08:23
@mmcky - yes, happy to do it.

**Comment by mmcky** [comment] 2017-04-12 01:58
@lbui01 can this be closed now?

**Comment by mmcky** [comment] 2017-04-12 02:00
Closing as duplicate of #128

**Closed by mmcky** 2017-04-12 02:00 UTC
Labels: tests
