### ISSUE TITLE
CI: Test Flake on test_random.test_covariance_game

### ISSUE THREAD

**Issue by rht** [QuantEcon/QuantEcon.py#567] opened 2021-01-09 02:10 UTC
I first observed this on CI on Python 3.7 on Windows. Turns out it has happened on Ubuntu as well: https://github.com/QuantEcon/QuantEcon.py/pull/566#issuecomment-757078096.
The log:
```
FAIL: test_random.test_covariance_game
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/runner/work/QuantEcon.py/QuantEcon.py/quantecon/game_theory/tests/test_random.py", line 33, in test_covariance_game
    assert_allclose(payoff_profile[i], payoff_profile[-1], atol=1e-8)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 1528, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=1e-08
```

**Comment by mmcky** [comment] 2021-01-17 23:42
@rht is this a current issue? On a recent PR all tests seem to be passing on all platforms?

**Comment by rht** [comment] 2021-01-18 00:05
Yes, this still happens occasionally.

**Comment by oyamad** [comment] 2021-01-19 01:19
@rht I can't reproduce the error on my mac machines. Could you possibly run the fix in #570?

**Comment by mmcky** [comment] 2021-01-19 01:30
thanks @oyamad -- I couldn't replicate either but I do see intermittent failures from time to time via CI. 
I think @rht is suggesting it fails stochastically?

**Comment by rht** [comment] 2021-01-19 01:33
Sorry for being unclear. Yes I meant the test fails stochastically, so the CI needs to be run several times in order to spot the error.

**Comment by rht** [comment] 2021-01-19 01:40
I will try to reproduce what the error size is on a Docker Ubuntu instance with 3.7.

**Comment by rht** [comment] 2021-01-19 02:02
Oh, actually, the absolute error is displayed in https://github.com/QuantEcon/QuantEcon.py/runs/1671233922?check_suite_focus=true#step:6:36 because `assert_allclose` has `verbose=True` by default.
```
Mismatched elements: 1 / 1 (100%)
Max absolute difference: 1.69718484e-08
Max relative difference: 3.725468e-07
 x: array(0.045556)
 y: array(0.045556)
```

The `reltol` probably needs to be increased as well.

**Comment by oyamad** [comment] 2021-01-19 02:18
[Documentation of `assert_allclose`](https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_allclose.html) says

> It compares the difference between `actual` and `desired` to ``atol + rtol * abs(desired)``.

The reported case should be covered by `atol=1e-7` (for any (nonnegative) value of `rtol`).

**Comment by rht** [comment] 2021-01-19 03:29
Ah, right, I didn't properly RTFM.

**Comment by oyamad** [comment] 2021-01-19 12:48
Basically, the test in consideration does the following:

```py
import numpy as np

atol = 1e-7

nums_actions = (2, 3, 4)
N = len(nums_actions)
mean = np.zeros(N)
cov = np.ones((N, N))

payoff_profile_array = np.random.multivariate_normal(mean, cov, nums_actions)

abs_diff_max = 0.

for a in np.ndindex(*nums_actions):
    payoff_profile = payoff_profile_array[a]
    for i in range(N-1):
        abs_diff = np.abs(payoff_profile[i] - payoff_profile[-1])
        if abs_diff > abs_diff_max:
            abs_diff_max = abs_diff

abs_diff_max < atol  # Ignoring `rtol`
```

On my mac machine, `abs_diff_max` is very small:

```py
abs_diff_max
```

```
4.440892098500626e-16
```

Note that `cov` is singular in this case (it is only positive semi-definite, not positive definite). It may be possible that `np.random.multivariate_normal` is not well behaved for such an input on some platforms.

**Comment by oyamad** [comment] 2021-01-20 05:15
On my other mac machine (with a different Python environment), I get numbers around `1e-8` for `abs_diff_max`.

**Comment by rht** [comment] 2021-01-20 06:17
I ran https://github.com/QuantEcon/QuantEcon.py/issues/567#issuecomment-762819805 on an Ubuntu 16.04 with Python 3.5.2, got the exact same `abs_diff_max`, 4.440892098500626e-16, regardless of the random seed.

**Comment by oyamad** [comment] 2021-01-20 06:31
@rht Thanks.

Anyway, the test is checking how `np.random.multivariate_normal` behaves against the above singular `cov`. Let us merge #570 and close this issue given that the test passes by the change of `atol=1e-7`.

**Comment by rht** [comment] 2021-02-02 01:39
The error also happens in 3.8: https://github.com/QuantEcon/QuantEcon.py/runs/1811166820?check_suite_focus=true#step:6:33.

**Closed** 2021-02-02 01:43 UTC

**Comment by oyamad** [comment] 2021-02-02 01:45
#570 having been merged it should work OK now.
