### ISSUE TITLE
Function value convergence test for `brent_max`

### ISSUE THREAD

**Issue by QBatista** [QuantEcon/QuantEcon.py#442] opened 2018-11-04 05:33 UTC
Without a function value convergence test, `brent_max` can fail on simple functions, for instance:

```python
>>> import quantecon as qe
>>> import numpy as np
>>> from numba import njit
>>> @njit
... def f(x): return 1.
... 
>>> qe.optimize.brent_max(f, -np.inf, np.inf)
(nan, 1.0, (0, 1))
```

Adding a function value convergence test should solve this issue.

**Comment by chrishyland** [comment] 2018-11-18 04:50
Hi @QBatista 
Sorry for the slow response but I just finished most of my exams for the semester this week. Will have more time to help out. 

Thank you for pointing that out. Just a few quick (naive) questions which would be helpful to enlighten me. What did you mean by function value convergence test? It would be helpful for you to direct me to some resources on this. Currently we checked whether if the iterations have gone on too long. In the cases of the above example, did you want the function to raise an exception instead?

Thank you.

**Comment by QBatista** [comment] 2018-11-19 06:54
@chrishyland By function value convergence test, I mean a termination condition that depends on the sequence of function evaluations. An example of an optimization method that uses such a test is [Nelder-Mead](https://github.com/QuantEcon/QuantEcon.py/blob/01ee68dbbd815b6275192a707377bb12e5e9da8f/quantecon/optimize/nelder_mead.py#L212), where during each iteration, the algorithm is terminated if after evaluating the function at each of the current simplex points, the highest and lowest function values are sufficiently close. In the example I gave above, all the function evaluations would be the same so checking convergence of the sequence would allow termination at a local maximum.

After checking SciPy's source code for `brent`, it seems that they are not using this type of tests, so it might be that it is actually not a good idea or is not feasible for this particular method. Nevertheless, their implementation works on the example above:

```python
>>> from scipy.optimize import minimize_scalar
>>> from numba import njit
>>> @njit
... def f(x): return 1
... 
>>> minimize_scalar(f)
     fun: 1
    nfev: 40
     nit: 36
 success: True
       x: 2.6180339603380443
```

Do you have an idea of what is causing this difference? If not, I can try to look into it.

**Comment by chrishyland** [comment] 2018-11-28 20:33
Hi @QBatista 

Another update. The issue is the line 
`fulc = a + golden_mean * (b-a)` near the top of the brent_max function. It's interesting because when you set the lower bound and upper bound a,b to infinity, the aforementioned line has issues. If you set the bounds to be finite numbers, then you start getting stuff that's kind of strange. When you change the bounds of brent_max, the maximizer returned increases as the bounds are relaxed (bounds are bigger). An example would be that

`qe.optimize.brent_max(f, -100,100)`
`qe.optimize.brent_max(f, -200,200)`

would return different results as the maximizer.

However for scipy's function, it consistently returns 2.618 as the optimal solution regardless of the bounds. 

Any suggestions on how do you want the behavior of the function to look like? Should we be getting the same answer as the Scipy function?

**Comment by chrishyland** [comment] 2018-12-02 04:08
Thank you for the explanation @QBatista . I was wondering about why those particular values were the maximizer for a function that is just a constant, your explanation cleared up alot.

I'm more than happy to keep working on resolving this issue, just let me know or if you have any other things you want me to take a look at, just let me know.

**Closed** 2018-12-11 00:53 UTC
